name: Build & Release Static FFmpeg on macOS ARM

on:
  push:
    tags:
      - 'v*'  # Triggers only on tag pushes like v1.0.0

jobs:
  build-ffmpeg:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone FFmpeg
        run: git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git

      - name: Install build dependencies
        run: |
          brew update
          brew install automake fdk-aac git lame libass libtool libvorbis libvpx \
            opencore-amr opus sdl2 shtool texi2html theora wget x264 x265 xvid nasm pkg-config

      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig" >> $GITHUB_ENV

      - name: Configure FFmpeg (static, only ffmpeg)
        run: |
          cd ffmpeg
          ./configure --prefix="$HOME/ffmpeg_build" --enable-gpl --enable-nonfree \
            --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame \
            --enable-libopus --enable-libvorbis --enable-libass --enable-libfdk-aac \
            --disable-shared --enable-static --disable-programs --enable-ffmpeg \
            --extra-cflags="-I/opt/homebrew/include" --extra-ldflags="-L/opt/homebrew/lib"

      - name: Build only ffmpeg binary
        run: |
          cd ffmpeg
          make -j$(sysctl -n hw.ncpu) ffmpeg

      - name: Copy ffmpeg binary
        run: |
          mkdir -p dist
          cp ffmpeg/ffmpeg dist/ffmpeg-macos-arm64

      - name: Upload ffmpeg binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-arm64
          path: dist/ffmpeg-macos-arm64

      - name: Create GitHub Release and upload binary
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/ffmpeg-macos-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}